In [80]:
import pandas as pd
import altair as alt
import matplotlib.pyplot as plt
import yfinance as yf
%matplotlib inline

days=20
ticker={
    'apple':'AAPL',
    'facebook':'FB',
    'google': 'GOOGL',
    'microsoft': 'MSFT',
    'amazon' : 'AMZN',
    'netflix' : 'NFLX'
}

def get_data(days,ticker):
    df=pd.DataFrame()
    for company in ticker.keys():
        tkr=yf.Ticker(ticker[company])
        hist=tkr.history(period=f'{days}d')
        hist.index=hist.index.strftime('%d %B %Y')
        hist=hist[['Close']]
        hist.columns=[company]
        hist=hist.T
        hist.index.name='Name'
        df=pd.concat([df,hist])
    
    return df

In [82]:
days=20
ticker={
    'apple':'AAPL',
    'facebook':'FB',
    'google': 'GOOGL',
    'microsoft': 'MSFT',
    'amazon' : 'AMZN',
    'netflix' : 'NFLX'
}

df=get_data(days,ticker)

In [83]:
companies=['apple','facebook','google','microsoft','amazon','netflix']
data=df.loc[companies]
data

Date,10 May 2022,11 May 2022,12 May 2022,13 May 2022,16 May 2022,17 May 2022,18 May 2022,19 May 2022,20 May 2022,23 May 2022,24 May 2022,25 May 2022,26 May 2022,27 May 2022,31 May 2022,01 June 2022,02 June 2022,03 June 2022,06 June 2022,07 June 2022
Name,,,,,,,,,,,,,,,,,,,,
apple,154.509995,146.500000,142.559998,147.110001,145.539993,149.240005,140.820007,137.350006,137.589996,143.110001,140.360001,140.520004,143.779999,149.639999,148.839996,148.710007,151.210007,145.380005,146.139999,148.710007
facebook,197.649994,188.740005,191.240005,198.619995,200.039993,202.619995,192.240005,191.289993,193.539993,196.229996,181.279999,183.830002,191.630005,195.130005,193.639999,188.639999,198.860001,190.779999,194.250000,195.649994
google,2287.899902,2272.050049,2256.879883,2321.010010,2288.899902,2329.459961,2237.989990,2207.679932,2178.159912,2229.760010,2119.399902,2116.100098,2155.850098,2246.330078,2275.239990,2277.840088,2352.449951,2290.820068,2336.409912,2342.989990
microsoft,268.873779,259.944550,254.756653,260.513245,260.892365,266.200012,254.080002,253.139999,252.559998,260.649994,259.619995,262.519989,265.899994,273.239990,271.869995,272.420013,274.579987,270.019989,268.750000,272.500000
amazon,108.859001,105.372002,106.930496,113.055000,110.810501,115.368500,107.112503,107.319000,107.591003,107.556999,104.099998,106.775002,111.077499,115.146500,120.209503,121.683998,125.511002,122.349998,124.790001,123.000000
netflix,177.660004,166.369995,174.309998,187.639999,186.509995,190.559998,177.190002,183.479996,186.350006,187.440002,180.339996,187.830002,191.399994,195.190002,197.440002,192.910004,205.089996,198.979996,197.139999,198.610001

In [84]:
data=data.T.reset_index()
data.head()

Name,Date,apple,facebook,google,microsoft,amazon,netflix
0,10 May 2022,154.509995,197.649994,2287.899902,268.873779,108.859001,177.660004
1,11 May 2022,146.500000,188.740005,2272.050049,259.944550,105.372002,166.369995
2,12 May 2022,142.559998,191.240005,2256.879883,254.756653,106.930496,174.309998
3,13 May 2022,147.110001,198.619995,2321.010010,260.513245,113.055000,187.639999
4,16 May 2022,145.539993,200.039993,2288.899902,260.892365,110.810501,186.509995

In [85]:
data=pd.melt(data, id_vars=['Date']).rename(
    columns={'value':'Stock Prices(USD)'}
)
data

             Date     Name  Stock Prices(USD)
0     10 May 2022    apple         154.509995
1     11 May 2022    apple         146.500000
2     12 May 2022    apple         142.559998
3     13 May 2022    apple         147.110001
4     16 May 2022    apple         145.539993
..            ...      ...                ...
115  01 June 2022  netflix         192.910004
116  02 June 2022  netflix         205.089996
117  03 June 2022  netflix         198.979996
118  06 June 2022  netflix         197.139999
119  07 June 2022  netflix         198.610001

[120 rows x 3 columns]

In [86]:
chart=(
    alt.Chart(data)
    .mark_line(opacity=0.8, clip=True)
    .encode(
        x="Date:T",
        y=alt.Y("Stock Prices(USD)",stack=None,scale=alt.Scale(domain=[0,300])),
        color='Name:N'
    )
)

In [87]:
chart

alt.Chart(...)